### ISSUE TITLE
Not running on commonMain of Kotlin Multiplatform Project

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#46] opened 2023-03-17 17:03 UTC
Rewrite is not running over commonMain sourceSet of a KMP. Example PR: https://github.com/nomisRev/rewrite-arrow/pull/32.

Running `./gradlew build :sample:rewriteRun` shows that the sources in `sample/src/commonMain/kotlin/org/example/example.kt` are not being rewritten or updated.

**Comment by traceyyoshima** [comment] 2023-03-21 00:59
Duplicate of https://github.com/openrewrite/rewrite-gradle-plugin/issues/172

**Closed by traceyyoshima** 2023-03-21 00:59 UTC
Labels: bug
