### ISSUE TITLE
Parsing error( or printer error) of generic type constraint

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite-kotlin#205] opened 2023-07-28 20:36 UTC
I see this error when working on space-visitor, and this is an example from IntelliJ formatting.

```java
    @Test
    void genericTypeConstraint() {
        rewriteRun(
          kotlin(
            """
              fun <T> foo(): Int where T: List<T> {
                  return 0
              }
              """
          )
        );
    }
```

Error
```
expected: 
  "fun <T> foo(): Int where T : List<T> {
      return 0
  }"
 but was: 
  "fun <T> foo(): ListInt where T : List<T>> foo(){
      return 0
  }"
```

**Comment by knutwannheden** [comment] 2023-09-01 13:39
The parser doesn't yet support the `where` clause, which can be used to [specify multiple upper bounds](https://kotlinlang.org/docs/generics.html#upper-bounds) for a generic type (although as in this example, it can also be used when only specifying a single upper bound).

With https://github.com/openrewrite/rewrite-kotlin/commit/7e8ef8b0ed2076b19bbcbcb8329494fe9a618c93 will now parse the `where` clause into a `Space` of some LST element. This is not yet correct, but it fixes the parse-to-print failure.

**Comment by knutwannheden** [comment] 2023-09-01 14:45
This is actually a duplicate of #160.

**Closed by knutwannheden** 2023-09-01 14:45 UTC
Labels: bug
